apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: roboshop-ebs
provisioner: ebs.csi.aws.com   # Change to your environment's provisioner
volumeBindingMode: WaitForFirstConsumer  # Delay volume binding until pod is scheduled
reclaimPolicy: Retain