apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mongodb 
spec:
  clusterIP: None
  selector:
    project: roboshop
    tier: db
    component: mongodb     
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017            
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: mongodb
  serviceName: "mongodb-headless"    #should attach headless service
  #pod definition
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mongodb  
    spec:
      containers:
        - name: mongodb
          image: mayurim334/mongodb:1.5.0
          volumeMounts:
            name: mongodb
            path: /data/db
      #PVC      
  volumeClaimTemplates:
  - metadata: 
      name: mongodb
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mongodb 
spec:
  selector:
    project: roboshop
    tier: db
    component: mongodb     
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017  





